### ISSUE TITLE
Publish snapshot artifacts to Sonatype fails

### ISSUE THREAD

**Issue by sormuras** [google/google-java-format#547]
The deployment of snapshot artifacts failed due to a `401 Unauthorized` error: https://github.com/google/google-java-format/runs/1455239922

_Note: a run on a fork reports "green", as the publish step is skipped:_ https://github.com/sormuras/google-java-format/actions/runs/383909185

These are the lines in question that trigger the upload:

https://github.com/google/google-java-format/blob/c1dd08d349b098f4bceb5b71aa1d6c2251de4f6d/.github/workflows/ci.yml#L50-L58

Reading https://github.com/actions/setup-java#publishing-using-apache-maven again, I think that all required credentials are given, passed, and written to correct configuration files. It should, if it worked, render the `util/settings.xml` superseded.

**Comment by cushon** [comment]
Looking at the example in those docs, `MAVEN_USERNAME` is commented as being an env variable, and there's a separate step that sets the env variable to the 'secret':

```
      env:
        MAVEN_USERNAME: maven_username123
        MAVEN_CENTRAL_TOKEN: ${{ secrets.MAVEN_CENTRAL_TOKEN }}
```

Maybe we need to add a similar `env:` section, or else use e.g. `${{ secrets. CI_DEPLOY_USERNAME }}` directly?

**Comment by sormuras** [comment]
> ... there's a separate step that sets the env variable to the 'secret': ...

Aye. That `env` section is missing. Do you want to add those two lines directly or should I create a PR?

```yaml
      - name: 'Publish'
        env:
          CI_DEPLOY_USERNAME: ${{ secrets.CI_DEPLOY_USERNAME }}
          CI_DEPLOY_PASSWORD: ${{ secrets.CI_DEPLOY_PASSWORD }}
        run: mvn source:jar deploy -B -DskipTests=true -Dinvoker.skip=true -Dmaven.javadoc.skip=true
```
